import type { SdkCrashInfo } from '@/service/SdkCrashStore';

const PASTES_DEV_API = 'https://api.pastes.dev/post';
const PASTES_DEV_BASE = 'https://pastes.dev/';

export async function uploadToPastesDev(content: string): Promise<string> {
  const response = await fetch(PASTES_DEV_API, {
    method: 'POST',
    headers: {
      'Content-Type': 'text/plain',
    },
    body: content,
  });

  if (!response.ok) {
    throw new Error(`Upload failed: HTTP ${response.status}`);
  }

  const data = await response.json() as { key?: string };
  if (!data.key) {
    throw new Error('Upload failed: no key in response');
  }

  return `${PASTES_DEV_BASE}${data.key}`;
}

export function formatCrashReport(crash: SdkCrashInfo): string {
  const lines: string[] = [];

  lines.push('=== BC Mod Manager — Crash Report ===');
  lines.push('');
  lines.push(`Type:     ${crash.type === 'hook' ? 'Mod Hook Crash' : 'Mod Patch Crash'}`);
  lines.push(`Mod:      ${crash.mod}`);
  lines.push(`Function: ${crash.fn}`);
  lines.push('');
  lines.push('--- Error ---');
  lines.push(crash.errorMessage);
  lines.push('');

  if (crash.stackFrames.length > 0) {
    lines.push('--- Stack Trace ---');
    lines.push(...crash.stackFrames);
    lines.push('');
  }

  if (crash.loadedMods.length > 0) {
    lines.push('--- Loaded Mods ---');
    lines.push(...crash.loadedMods.map(m => `  ${m}`));
    lines.push('');
  }

  lines.push(`Generated by BC Mod Manager`);

  return lines.join('\n');
}
